### PR TITLE
ensure the /etc/hosts entries

### PR DESCRIPTION
**Pull request by troy2914**
this requires icpc_wf.yml group_vars from #3

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]

**Comment by vmcj** [comment]
For DOMjudge we generate this file out of the inventory which I think will require less bookkeeping. The nice thing with adding it to the inventory is that you can use it as canary host to check if sync processes etc. do work.

**Comment by troy2914** [comment]
> For DOMjudge we generate this file out of the inventory which I think will require less bookkeeping. The nice thing with adding it to the inventory is that you can use it as canary host to check if sync processes etc. do work.

I don't think we would want all machines having the full hosts table.  This is for non-domjudge machines, especially :)

**Comment by nickygerritsen** [comment]
> > For DOMjudge we generate this file out of the inventory which I think will require less bookkeeping. The nice thing with adding it to the inventory is that you can use it as canary host to check if sync processes etc. do work.
> 
> I don't think we would want all machines having the full hosts table. This is for non-domjudge machines, especially :)

We can generate it for only select groups of course. It would make it a bit more dynamic sounds if the ip of one of these machine changes. But not a major issue

**Comment by troy2914** [comment]
> > > For DOMjudge we generate this file out of the inventory which I think will require less bookkeeping. The nice thing with adding it to the inventory is that you can use it as canary host to check if sync processes etc. do work.
> > 
> > 
> > I don't think we would want all machines having the full hosts table. This is for non-domjudge machines, especially :)
> 
> We can generate it for only select groups of course. It would make it a bit more dynamic sounds if the ip of one of these machine changes. But not a major issue

well bottom line, is there something you would like for this to be changed?  Or is it good as is?

**Comment by nickygerritsen** [comment]
For me it’s fine

**Comment by troy2914** [comment]
ok, waiting for #4 that sets the baseip.

**Review by vmcj — APPROVED** [review]

**Pull request merged**
